### ISSUE TITLE
Compile fails in Riviera-PRO

### ISSUE THREAD

**Issue by LeChuck42** [UVVM/UVVM_Light#4]
The compile script fails in Rivirea-PRO with
```
# SCRIPTER: Error: compile.do : (14, 1): invalid command name "quietly"
# SCRIPTER: Error: compile.do : (14, 1): Script execution terminated due to error(s).
```

**Comment by mariuselv** [comment]
Hi,
this seems to be a bug. I will make a fix and publish it soon.

Br,
Marius

**Comment by mariuselv** [comment]
Or even better - a pull-request 👍

**Comment by LeChuck42** [comment]
apparently this was merged and then overwritten back to the previous state on 736eafb2d248a3f9a4528440e31a0f75b8c082ce
